name: SonarQube analysis Server InOffice

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  Send-to-Sonar-Server-InOffice:
    runs-on: ubuntu-latest

    steps:
      - name: Zerotier Configuration
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ vars.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Ping to Nexus Sever InOffice
        shell: bash
        run: |
          count=3
          while ! ping -c 3 ${{ vars.SONARQUBE_IP_SERVER }} ; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done
          echo "success ping connection to server inOffice ${{ vars.SONARQUBE_IP_SERVER }}"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.projectName="${{ vars.SONAR_PROJECT_NAME }}"
            -Dsonar.sources=.
            -X
